server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root123456
  redis:
    host: 172.16.173.156
    database: 1
    port: 6379
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句
