server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    ##如果是集群环境，或者是分布式项目的话，localhost必须要改成你服务器的内网ip
    password: root